### ISSUE TITLE
Just tried on my project and got an error

### ISSUE THREAD

**Issue by jourdain** [wix/yarn-bin-fix#1]
```sh
$ git clone https://github.com/Kitware/paraviewweb.git
$ cd paraviewweb
$ yarn
$ yarn-bin-fix
running yarn-bin-fix...
bin dir is /.../paraviewweb/node_modules/.bin
linking /.../paraviewweb/node_modules/.bin/acorn
linking /.../paraviewweb/node_modules/.bin/babylon
linking /.../paraviewweb/node_modules/.bin/brfs
linking /.../paraviewweb/node_modules/.bin/cleancss
linking /.../paraviewweb/node_modules/.bin/git-cz
linking /.../paraviewweb/node_modules/.bin/commitizen
linking /.../paraviewweb/node_modules/.bin/esparse
linking /.../paraviewweb/node_modules/.bin/esvalidate
linking /.../paraviewweb/node_modules/.bin/commonize
linking /.../paraviewweb/node_modules/.bin/semver
linking /.../paraviewweb/node_modules/.bin/csso
linking /.../paraviewweb/node_modules/.bin/uglifyjs
linking /.../paraviewweb/node_modules/.bin/esparse
linking /.../paraviewweb/node_modules/.bin/esvalidate
linking /.../paraviewweb/node_modules/.bin/dateformat
linking /.../paraviewweb/node_modules/.bin/electron-download
linking /.../paraviewweb/node_modules/.bin/envify
linking /.../paraviewweb/node_modules/.bin/errno
linking /.../paraviewweb/node_modules/.bin/esgenerate
linking /.../paraviewweb/node_modules/.bin/escodegen
linking /.../paraviewweb/node_modules/.bin/eslint
linking /.../paraviewweb/node_modules/.bin/acorn
linking /.../paraviewweb/node_modules/.bin/esparse
linking /.../paraviewweb/node_modules/.bin/esvalidate
linking /.../paraviewweb/node_modules/.bin/esparse
linking /.../paraviewweb/node_modules/.bin/esvalidate
linking /.../paraviewweb/node_modules/.bin/extract-zip
linking /.../paraviewweb/node_modules/.bin/acorn
linking /.../paraviewweb/node_modules/.bin/findup
linking /.../paraviewweb/node_modules/.bin/har-validator
linking /.../paraviewweb/node_modules/.bin/mkdirp
linking /.../paraviewweb/node_modules/.bin/node-pre-gyp
linking /.../paraviewweb/node_modules/.bin/uuid
linking /.../paraviewweb/node_modules/.bin/nopt
linking /.../paraviewweb/node_modules/.bin/rc
linking /.../paraviewweb/node_modules/.bin/rimraf
linking /.../paraviewweb/node_modules/.bin/semver
linking /.../paraviewweb/node_modules/.bin/sshpk-conv
linking /.../paraviewweb/node_modules/.bin/sshpk-sign
linking /.../paraviewweb/node_modules/.bin/sshpk-verify
linking /.../paraviewweb/node_modules/.bin/strip-json-comments
linking /.../paraviewweb/node_modules/.bin/git-head
linking /.../paraviewweb/node_modules/.bin/git-refs
linking /.../paraviewweb/node_modules/.bin/glslify
linking /.../paraviewweb/node_modules/.bin/glslify
linking /.../paraviewweb/node_modules/.bin/glslify
linking /.../paraviewweb/node_modules/.bin/uglifyjs
linking /.../paraviewweb/node_modules/.bin/handlebars
linking /.../paraviewweb/node_modules/.bin/html-minifier
linking /.../paraviewweb/node_modules/.bin/uglifyjs
linking /.../paraviewweb/node_modules/.bin/html-minifier
linking /.../paraviewweb/node_modules/.bin/image-size
linking /.../paraviewweb/node_modules/.bin/istanbul
linking /.../paraviewweb/node_modules/.bin/js-yaml
linking /.../paraviewweb/node_modules/.bin/jsonlint
linking /.../paraviewweb/node_modules/.bin/semver
linking /.../paraviewweb/node_modules/.bin/loose-envify
linking /.../paraviewweb/node_modules/.bin/gl-style-migrate
linking /.../paraviewweb/node_modules/.bin/gl-style-validate
linking /.../paraviewweb/node_modules/.bin/gl-style-format
linking /.../paraviewweb/node_modules/.bin/gl-style-composite
linking /.../paraviewweb/node_modules/.bin/mime
linking /.../paraviewweb/node_modules/.bin/uglifyjs
linking /.../paraviewweb/node_modules/.bin/minstache
linking /.../paraviewweb/node_modules/.bin/ncp
linking /.../paraviewweb/node_modules/.bin/uuid
linking /.../paraviewweb/node_modules/.bin/strip-ansi
linking /.../paraviewweb/node_modules/.bin/semver
undefined:1



SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at _.forEach (/usr/local/lib/node_modules/yarn-bin-fix/bin/yarn-bin-fix:33:24)
    at arrayEach (/usr/local/lib/node_modules/yarn-bin-fix/node_modules/lodash/lodash.js:530:11)
    at Function.forEach (/usr/local/lib/node_modules/yarn-bin-fix/node_modules/lodash/lodash.js:9319:14)
    at linkExecutables (/usr/local/lib/node_modules/yarn-bin-fix/bin/yarn-bin-fix:31:5)
    at run (/usr/local/lib/node_modules/yarn-bin-fix/bin/yarn-bin-fix:58:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/yarn-bin-fix/bin/yarn-bin-fix:62:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
```

**Comment by DanielZlotin** [comment]
hmm.. weird.. this means one of the package.json files is invalid (inside your node_modules)... can you try to debug? I'll be happy for any help

**Comment by jourdain** [comment]
;-) thanks Daniel, I'll try to investigate a bit more... But agree with you, that's weird...
Maybe having a nice ignore (try/catch) to go further might be enough?

Anyway, thanks for your feedback on my issue on yarn hopefully they will tackle it at some point...

**Comment by DanielZlotin** [comment]
I'm out of the office, tomorrow will get back and fix it

**Comment by DanielZlotin** [comment]
@jourdain Fixed in 0.1.15 - test it out plz

**Comment by jourdain** [comment]
Much better but for some reason it did not add "webpack" to the bin directory.

``` sh
running yarn-bin-fix...
bin dir is /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/acorn
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/babylon
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/brfs
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/cleancss
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/git-cz
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/commitizen
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/esparse
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/esvalidate
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/commonize
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/semver
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/csso
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/uglifyjs
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/dateformat
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/electron-download
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/envify
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/errno
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/esgenerate
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/escodegen
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/eslint
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/extract-zip
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/findup
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/har-validator
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/mkdirp
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/node-pre-gyp
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/uuid
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/nopt
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/rc
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/rimraf
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/sshpk-conv
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/sshpk-sign
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/sshpk-verify
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/strip-json-comments
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/git-head
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/git-refs
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/glslify
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/handlebars
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/html-minifier
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/image-size
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/istanbul
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/js-yaml
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/jsonlint
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/loose-envify
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/gl-style-migrate
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/gl-style-validate
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/gl-style-format
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/gl-style-composite
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/mime
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/minstache
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/ncp
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/strip-ansi
can't parse /Users/seb/Documents/code/Web2/paraviewweb/node_modules/npmconf/test/fixtures/package.json
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/nugget
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/pbf
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/pretty-bytes
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/quote-stream
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/semantic-release
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/dbfcat
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/shpcat
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/shp2json
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/strip-indent
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/svgo
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/tap-out
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/tap-summary
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/tidy-markdown
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/topojson
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/topojson-geojson
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/topojson-group
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/topojson-merge
linking /Users/seb/Documents/code/Web2/paraviewweb/node_modules/.bin/topojson-svg
DONE
```

**Comment by DanielZlotin** [comment]
@jourdain Can you please paste the contents of `can't parse /Users/seb/Documents/code/Web2/paraviewweb/node_modules/npmconf/test/fixtures/package.json`? I think there's some problems with this json

**Comment by DanielZlotin** [comment]
Oh I just saw that they accepted the PR 🎉 
So this project is deprecated starting from their next release (provided it's actually fixed)
